### PR TITLE
chore: make C# grpc files end with Grpc.g.cs

### PR DESCRIPTION
**Pull request by viacheslav-rostovtsev**
instead of just Grpc.cs (by default)

### CODE REVIEW

**Review by jskeet — APPROVED** [review]
This is fine so long as the version of the gRPC generator being used is appropriate. I don't think it's currently using a sufficiently recent version though - we need 2.39.1 IIRC.

Is that handled elsewhere?

**Comment by viacheslav-rostovtsev** [comment]
Couple points:
1. grpc version -- I assume you meant 1.39.1 since grpc's github tags are currently at 1.40.0
2. Which version is used -- this is not defined here. Bazel is lenient with the references, as long as every symbol gets resolved by the time the rule is invoked. 
The specific symbol here is `@com_github_grpc_grpc` and as one can [see by searching](https://github.com/googleapis/rules_gapic/search?q=com_github_grpc_grpc) it's not defined in this repo.
Where is it defined? For prod library generation I think the answer is [googleapis/googleapis WORKSPACE](https://github.com/googleapis/googleapis/blob/master/WORKSPACE#L147-L151). It's an old version and we'll have to update it when we will bring this update in.

NB: for our own gapic-generator-csharp/bazel_example `@com_github_grpc_grpc` is defined [in the bazel_example WORKSPACE](https://github.com/googleapis/gapic-generator-csharp/blob/3300cb64cf712ebd7fb94fa5cb3f67b5eae3163e/bazel_example/WORKSPACE.bazel#L43-L51), the version there is 1.39.1, I tested there and the filenames got changed.

Before: 
```
❯ tree ~/src/gapic-generator-csharp/bazel_example/example_csharp_pkg 
/home/virost/src/gapic-generator-csharp/bazel_example/example_csharp_pkg
├── Example
│   ├── ExampleClient.g.cs
│   ├── Example.csproj
│   ├── Example.g.cs
│   ├── ExampleGrpc.cs
│   └── ExampleResourceNames.g.cs
├── Example.Snippets
```

After
```
❯ tree ~/src/gapic-generator-csharp/bazel_example/example_csharp_pkg                                                                                                                                                                                                                                                                                                                                                                        
/home/virost/src/gapic-generator-csharp/bazel_example/example_csharp_pkg                                                                                                                                                                                                                                                                                                                                                                    
├── Example                                                                                                                                                                                                                                                                                                                                                                                                                                 
│   ├── ExampleClient.g.cs                                                                                                                                                                                                                                                                                                                                                                                                                  
│   ├── Example.csproj                                                                                                                                                                                                
│   ├── Example.g.cs                                                                                                                                                                                                  
│   ├── ExampleGrpc.g.cs                                                                                                                                                                                              
│   └── ExampleResourceNames.g.cs                                                                                                                                                                                     
├── Example.Snippets                                            
```

I hope this made things clearer.

**Review by vam-google — APPROVED** [review]
LGTM

**Comment by jskeet** [comment]
The major version is 1.39.1 for the main project, but 2.39.1 for the NuGet packages as .NET took a breaking change a while ago. I only ever use the NuGet packages, so that's why I always think in 2.x :)

**Review by jskeet — APPROVED** [review]
LGTM - I assume you'll manage updating the version used in the other workspace.

**Pull request merged**
