### PR TITLE
feat: generate C++ rules

### PR DESCRIPTION
**Pull request by coryan**
This adds support to generate the C++ rules for basic proto and gRPC
libraries.

/fyi: @devjgm @scotthart

### CODE REVIEW

**Review by noahdietz — COMMENTED** [review]
LGTM. @vam-google can you review/Approve please?

**Review by vam-google — APPROVED** [review]
LGTM, but please note that this will start adding C++ targets to everyting increasing build time.

Is there a way to add them conditionally, only when C++ rules a needed (if there is such signal at all in the input)?

**Comment by coryan** [comment]
Well, we are only interested in rules for Cloud services.  We are planning to implement client libraries (generated) for **all** Cloud services. If there is a way to generate "just" for Cloud then let me know how, I would be happy to change the PR to do so.

Note: I cannot merge this PR myself.

**Comment by noahdietz** [comment]
@vam-google if the goal is to generate for all Cloud services, that is a majority of APIs in googleapis. I'm not sure that gating generation of the C++ rules is worth the extra complexity. We'd need to add either another template for Cloud, or a conditional into the template (which we have avoided to date and I'd like to keep it that way personally).

I wonder if we are already paying the most expensive part of generating a new language - compilation of the dependencies/tools - since C++ tooling is already part of the WORKSPACE. Adding these grpc/proto rules probably won't increase things drastically (totally guessing though).

**Comment by devjgm** [comment]
As @coryan mentioned, we do plan C++ libraries for ~every services, just the same as all the other supported languages. Ideally, I think C++ shouldn't be treated any differently than, say, Java.

**Pull request merged**
