### PR TITLE
feat(build_gen): add service_yaml to java_gapic_library

### PR DESCRIPTION
**Pull request by noahdietz**
Generate `java_gapic_library` with `service_yaml` attribute populated with the Service config YAML file label.

This is necessary for upcoming mixins support.

Also adds `--test_output=errors` to the `bazel test` invocation so that we can see in the Action logs what actually failed.

### CODE REVIEW

**Comment by noahdietz** [comment]
Bump @miraleung

**Comment by miraleung** [comment]
Will revisit this after removing the allowlist from the Java microgenerator.

**Comment by miraleung** [comment]
Will ack this when we have a new release of the Java microgenerator (ETA EOW).

**Review by miraleung — APPROVED** [review]
LGTM with the 1.0.15 release of the Java microgenerator.

**Pull request merged**
